/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-02-15 06:23:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("  <!-- ager ta -->\r\n");
      out.write("  <div class=\"footer text-center\">\r\n");
      out.write(" <div class=\"container\">\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <!-- Footer Location-->\r\n");
      out.write("                    <div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">Location</h4>\r\n");
      out.write("                        <p class=\"lead mb-0\"> \r\n");
      out.write("                            <h5>Dhaka Head Office</h5>        \r\n");
      out.write("                            King Digital Recharge Limited\r\n");
      out.write("                            <br />\r\n");
      out.write("                            10, Main Road (3rd Floor)\r\n");
      out.write("                            <br />\r\n");
      out.write("                            Mohammadia Housing Ltd\r\n");
      out.write("                            <br />\r\n");
      out.write("                            Mohammadpur, Dhaka-1207, Bangladesh.\r\n");
      out.write("                            <br />\r\n");
      out.write("                            <strong>Phone:</strong> 01611204080, 01400922942, 01924754023\r\n");
      out.write("                            <br />\r\n");
      out.write("                            <strong>Email:</strong> info@rkingroup.com\r\n");
      out.write("                            <br />\r\n");
      out.write("                            <strong>Web:</strong> rkingroup.com\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Footer Social Icons-->\r\n");
      out.write("                    <div class=\"col-lg-4 mb-5 mb-lg-0\">\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">Around the Web</h4>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"https://www.google.com/\"><i class=\"fab fa-fw fa-google\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"https://www.facebook.com/\"><i class=\"fab fa-fw fa-facebook-f\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"https://twitter.com/\"><i class=\"fab fa-fw fa-twitter\"></i></a>\r\n");
      out.write("                        <a class=\"btn btn-outline-light btn-social mx-1\" href=\"https://www.linkedin.com/\"><i class=\"fab fa-fw fa-linkedin-in\"></i></a>\r\n");
      out.write("                      \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Footer About Text-->\r\n");
      out.write("                    <div class=\"col-lg-4\">\r\n");
      out.write("                        <h4 class=\"text-uppercase mb-4\">About KDRL</h4>\r\n");
      out.write("                        <p class=\"lead mb-0\">\r\n");
      out.write("                            King Digital Recharge Limited (KDRL) is approved by Bangladesh Telecommunication Regulatory Commission (BTRC).\r\n");
      out.write("                            <br />\r\n");
      out.write("                            <a href=\"https://rkingroup.com/Home.aspx\">King Digital Recharge Limited</a>\r\n");
      out.write("                            .\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>   \r\n");
      out.write("            <!-- Copyright Section-->\r\n");
      out.write("        <div class=\"copyright py-4 text-center text-white\">\r\n");
      out.write("            <div class=\"container\"><small>© King Digital Recharge 2014</small></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->\r\n");
      out.write("        <div class=\"scroll-to-top d-lg-none position-fixed\">\r\n");
      out.write("            <a class=\"js-scroll-trigger d-block text-center text-white rounded\" href=\"#page-top\"><i class=\"fa fa-chevron-up\"></i></a>\r\n");
      out.write("        </div>\r\n");
      out.write("     ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
