/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-02-17 10:52:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.pages.module_002dsalaryUpdate;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class salaryUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("       <!-- Masthead-->\r\n");
      out.write("        <header class=\"masthead bg-primary text-white text-center\">\r\n");
      out.write("            <div class=\"container d-flex align-items-center flex-column\">\r\n");
      out.write("                <!-- Masthead Avatar Image-->\r\n");
      out.write("                <img class=\"masthead-avatar mb-5\" src=\"assets/img/kdrl.png\" alt=\"\" />\r\n");
      out.write("                <!-- Masthead Heading-->\r\n");
      out.write("                <h2 class=\"masthead-heading text-uppercase mb-0\">King Digital Recharge Limited.</h2>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom divider-light\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Masthead Subheading-->\r\n");
      out.write("                <p class=\"masthead-subheading font-weight-light mb-0\">We Think & Work Digitally</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("            <!-- Application-->\r\n");
      out.write("    <div class=\"page-wrapper bg-gra-03 p-t-45 p-b-50\">\r\n");
      out.write("                <div class=\"wrapper wrapper--w790\">\r\n");
      out.write("                    <div class=\"card card-5\">\r\n");
      out.write("                    \r\n");
      out.write("                    <!--------------- logo ---------------------> \r\n");
      out.write("                        <div class=\"row center\">\r\n");
      out.write("                     <div class=\"col-12\">\r\n");
      out.write("                          <div class=\"card-heading\">\r\n");
      out.write("                            <h2 class=\"title\">Salary Update Form</h2>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                        <div class=\"card-body\">\r\n");
      out.write("                            <form id=\"salaryFormUpdate\"  class=\"form-horizontal\">\r\n");
      out.write("                                <div class=\"form-row m-b-55\">\r\n");
      out.write("                                \r\n");
      out.write("                                  <!---------------  Employee Name --------------------->\r\n");
      out.write("                                    <div class=\"col-lg-12\">\r\n");
      out.write("                                \t\t<div class=\"input-group input-group-sm pt-1\">\r\n");
      out.write("                                    \t\t<div class=\"input-group-prepend\">\r\n");
      out.write("                                        \t\t<span class=\"input-group-text\"> Employee Name</span>\r\n");
      out.write("                                    \t\t</div>\r\n");
      out.write("                                        <input name=\"employee_name\" id=\"employee_name\" type=\"text\" class=\"form-control\" placeholder=\"Text.. \" >\r\n");
      out.write("                                \t\t</div>\r\n");
      out.write("                          \t\t\t</div>\r\n");
      out.write("                              \r\n");
      out.write("                              <!---------------  Employee Email --------------------->  \r\n");
      out.write("                                <div class=\"col-lg-12\">\r\n");
      out.write("                                \t\t<div class=\"input-group input-group-sm pt-1\">\r\n");
      out.write("                                    \t\t<div class=\"input-group-prepend\">\r\n");
      out.write("                                        \t\t<span class=\"input-group-text\"> Employee Email</span>\r\n");
      out.write("                                    \t\t</div>\r\n");
      out.write("                                        <input name=\"employee_email\" id=\"employee_email\" type=\"text\" class=\"form-control\" placeholder=\"Text.. \" readonly>\r\n");
      out.write("                                \t\t</div>\r\n");
      out.write("                          \t\t\t</div>\r\n");
      out.write("                                <!---------------  Class Name --------------------->  \r\n");
      out.write("                                <div class=\"col-lg-12\">\r\n");
      out.write("                                \t\t<div class=\"input-group input-group-sm pt-1\">\r\n");
      out.write("                                    \t\t<div class=\"input-group-prepend\">\r\n");
      out.write("                                        \t\t<span class=\"input-group-text\"> Class Name</span>\r\n");
      out.write("                                    \t\t</div>\r\n");
      out.write("                                    \t\t<select id=\"class_name\" name=\"class_name\" class=\"form-control\" placeholder=\"Select Class \">\r\n");
      out.write("                                    \t\t\t\t<option value=\"..\">Select Class</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Class_1\">Class 1</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Class_2\">Class 2</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Class_3\">Class 3</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"Class_4\">Class 4</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("                                    \t\t<!----<input name=\"class_name\" id=\"class_name\" type=\"text\" class=\"form-control\" placeholder=\" \" >---->\r\n");
      out.write("                                        \r\n");
      out.write("                                \t\t</div>\r\n");
      out.write("                          \t\t\t</div>\r\n");
      out.write("                                <!---------------  salary ---------------------> \r\n");
      out.write("                                <div class=\"col-lg-12\">\r\n");
      out.write("                                \t\t<div class=\"input-group input-group-sm pt-1\">\r\n");
      out.write("                                    \t\t<div class=\"input-group-prepend\">\r\n");
      out.write("                                        \t\t<span class=\"input-group-text\"> Salary</span>\r\n");
      out.write("                                    \t\t</div>\r\n");
      out.write("                                        <input name=\"salary\" id=\"salary\" type=\"text\" class=\"form-control\" placeholder=\"Text..\" >\r\n");
      out.write("                                \t\t</div>\r\n");
      out.write("                          \t\t\t</div>\r\n");
      out.write("                          \t\t<!--------------- Travel Allowance --------------------->\r\n");
      out.write("                          \t\t<div class=\"col-lg-12\">\r\n");
      out.write("                                \t\t<div class=\"input-group input-group-sm pt-1\">\r\n");
      out.write("                                    \t\t<div class=\"input-group-prepend\">\r\n");
      out.write("                                        \t\t<span class=\"input-group-text\"> Travel Allowance</span>\r\n");
      out.write("                                    \t\t</div>\r\n");
      out.write("                                        <input name=\"travel_allowance\" id=\"travel_allowance\" type=\"text\" class=\"form-control\" placeholder=\" Text..\" >\r\n");
      out.write("                                \t\t</div>\r\n");
      out.write("                          \t\t\t</div>\r\n");
      out.write("                          \t\t\t<!--------------- medical_allowance --------------------->\r\n");
      out.write("                          \t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("                                \t\t<div class=\"input-group input-group-sm pt-1\">\r\n");
      out.write("                                    \t\t<div class=\"input-group-prepend\">\r\n");
      out.write("                                        \t\t<span class=\"input-group-text\"> Medical Allowance</span>\r\n");
      out.write("                                    \t\t</div>\r\n");
      out.write("                                        <input name=\"medical_allowance\" id=\"medical_allowance\" type=\"text\" class=\"form-control\" placeholder=\"Text.. \" >\r\n");
      out.write("                                \t\t</div>\r\n");
      out.write("                          \t\t\t</div>\r\n");
      out.write("                          \t\t\t<!--------------- overtime_allowance --------------------->\r\n");
      out.write("                          \t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("                                \t\t<div class=\"input-group input-group-sm pt-1\">\r\n");
      out.write("                                    \t\t<div class=\"input-group-prepend\">\r\n");
      out.write("                                        \t\t<span class=\"input-group-text\"> Overtime Allowance</span>\r\n");
      out.write("                                    \t\t</div>\r\n");
      out.write("                                        <input name=\"overtime_allowance\" id=\"overtime_allowance\" type=\"text\" class=\"form-control\" placeholder=\" Text..\" >\r\n");
      out.write("                                \t\t</div>\r\n");
      out.write("                          \t\t\t</div>\r\n");
      out.write("                          \t\t\t<!--------------- Month --------------------->\r\n");
      out.write("                          \t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("                                \t\t<div class=\"input-group input-group-sm pt-1\">\r\n");
      out.write("                                    \t\t<div class=\"input-group-prepend\">\r\n");
      out.write("                                        \t\t<span class=\"input-group-text\"> Month</span>\r\n");
      out.write("                                    \t\t</div>\r\n");
      out.write("                                    \t\t<select id=\"month\" name=\"month\" class=\"form-control\" placeholder=\"Text.. \">\r\n");
      out.write("                                    \t\t\t\t<option value=\"..\">Select month</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"january\">January</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"february\">February</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"march\">March</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"april\">April</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"may\">May</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"june\">June</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"july\">July</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"august\">August</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"september\">September</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"october\">October</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"november\">November</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"december\">December</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("                      <!--------<input name=\"month\" id=\"month\" type=\"text\" class=\"form-control\" placeholder=\" \" >-------->\r\n");
      out.write("                                        \r\n");
      out.write("                                \t\t</div>\r\n");
      out.write("                          \t\t\t</div>\r\n");
      out.write("                          \t\t\t<!--------------- Current Year --------------------->\r\n");
      out.write("                          \t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("                                \t\t<div class=\"input-group input-group-sm pt-1\">\r\n");
      out.write("                                    \t\t<div class=\"input-group-prepend\">\r\n");
      out.write("                                        \t\t<span class=\"input-group-text\"> Current Year</span>\r\n");
      out.write("                                    \t\t</div>\r\n");
      out.write("                                    \t\t<select id=\"current_year\" name=\"current_year\" class=\"form-control\" placeholder=\"Text..\">\r\n");
      out.write("                                    \t\t\t\t<option value=\"..\">Select Year</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"a\">2015</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"s\">2016</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"d\">2017</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"f\">2018</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"g\">2019</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"h\">2020</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"j\">2021</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"k\">2022</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"q\">2023</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"w\">2024</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"e\">2025</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"r\">2026</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"t\">2027</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"y\">2028</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"u\">2029</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"i\">2030</option>\r\n");
      out.write("  \t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("                             <!---<input name=\"current_year\" id=\"current_year\" type=\"text\" class=\"form-control\" placeholder=\" \" >---->\r\n");
      out.write("                                    \t\t\r\n");
      out.write("                                \t\t</div>\r\n");
      out.write("                          \t\t\t</div>\r\n");
      out.write("                                <!---------------  Button ---------------------> \r\n");
      out.write("                                <div class=\"modal-footer\">\r\n");
      out.write("                                <button type=\"submit\"  class=\"btn btn--radius-2 btn--red-2\" id= \"btnSubmitForm\" style=\"background-color:#b721ff !important\">Submit</button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
