/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.34
 * Generated at: 2021-02-17 05:53:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.pages.module_002dabout;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("        <!-- Navigation-->\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Masthead-->\r\n");
      out.write("           <header class=\"masthead bg-primary text-white text-center\">\r\n");
      out.write("            <div class=\"container d-flex align-items-center flex-column\">\r\n");
      out.write("                <!-- Masthead Avatar Image-->\r\n");
      out.write("                <img class=\"masthead-avatar mb-5\" src=\"assets/img/kdrl.png\" alt=\"\" />\r\n");
      out.write("                <!-- Masthead Heading-->\r\n");
      out.write("                <h2 class=\"masthead-heading text-uppercase mb-0\">King Digital Recharge Limited.</h2>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom divider-light\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Masthead Subheading-->\r\n");
      out.write("                <p class=\"masthead-subheading font-weight-light mb-0\">We Think & Work Digitally</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </header>\r\n");
      out.write("        <!-- Portfolio Section-->\r\n");
      out.write("        <section class=\"page-section portfolio\" id=\"portfolio\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- Portfolio Section Heading-->\r\n");
      out.write("                <h2 class=\"page-section-heading text-center text-uppercase text-secondary mb-0\"> Dealership at KDRL</h2>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Portfolio Grid Items-->\r\n");
      out.write("                <div class=\"row justify-content-center\">\r\n");
      out.write("                    <!-- Portfolio Item 1-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal1\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-phone fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/gp.png\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 2-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal2\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-phone fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/bl.png\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 3-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal2\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-phone fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/airtel.png\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 4-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal2\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-phone fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/teletalk.png\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- Portfolio Item 5-->\r\n");
      out.write("                    <div class=\"col-md-6 col-lg-4 mb-5\">\r\n");
      out.write("                        <div class=\"portfolio-item mx-auto\" data-toggle=\"modal\" data-target=\"#portfolioModal2\">\r\n");
      out.write("                            <div class=\"portfolio-item-caption d-flex align-items-center justify-content-center h-100 w-100\">\r\n");
      out.write("                                <div class=\"portfolio-item-caption-content text-center text-white\"><i class=\"fas fa-phone fa-3x\"></i></div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"assets/img/portfolio/robi.png\" alt=\"\" />\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <!-- About Section-->\r\n");
      out.write("        <section class=\"page-section bg-primary text-white mb-0\" id=\"about\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <!-- About Section Heading-->\r\n");
      out.write("                <h2 class=\"page-section-heading text-center text-uppercase text-white\">About</h2>\r\n");
      out.write("                <!-- Icon Divider-->\r\n");
      out.write("                <div class=\"divider-custom divider-light\">\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                    <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("                    <div class=\"divider-custom-line\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- About Section Content-->\r\n");
      out.write("                <div class=\"row\">\r\n");
      out.write("                    <p style=\"font-size: 20px;\">King Digital Recharge Limited (KDRL) is a private limited company which is registered under\r\n");
      out.write("                         Joint Stock Company of Bangladesh Government since 2012. It is the only multi-recharge company \r\n");
      out.write("                         in Bangladesh which is approved by Bangladesh Telecommunication Regulatory Commission (BTRC). \r\n");
      out.write("                         KDRL has developed a unique solution for balance recharge (both pre and post-paid) to all mobile\r\n");
      out.write("                          operators by using only a single mobile phone. It is the only solution which can benefit \r\n");
      out.write("                          both agents/retailers or customers at the same time.</p>\r\n");
      out.write("                       </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </section>\r\n");
      out.write("<!-- Problem of existing systems-->\r\n");
      out.write("<section class=\"page-section bg-primary text-white mb-0\" id=\"about\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- Problem of existing systems Section Heading-->\r\n");
      out.write("        <h2 class=\"page-section-heading text-center text-uppercase text-white\">Problem of existing systems</h2>\r\n");
      out.write("        <!-- Icon Divider-->\r\n");
      out.write("        <div class=\"divider-custom divider-light\">\r\n");
      out.write("            <div class=\"divider-custom-line\"></div>\r\n");
      out.write("            <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("            <div class=\"divider-custom-line\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Problem of existing systems Section Content-->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <div class=\"col-lg-4 ml-auto\"><p class=\"lead\">1. For most of the agents/retailers is it difficult to have individual account with all mobile operators.\r\n");
      out.write("                <br> 2. There is a burden to buy recharge balance daily from the distributor's agents regardless agents/retailers could sell previous recharge balance or not.\r\n");
      out.write("            </p></div>\r\n");
      out.write("            <div class=\"col-lg-4 mr-auto\"><p class=\"lead\">3. It is cumbersome to maintain all different accounts.\r\n");
      out.write("                 <br>4. Agent/retailer require 6 mobile phones if they have account with six mobile operators.\r\n");
      out.write("                <br> 5. Requires more investment buying recharge balance and mobile phones if they have many different accounts.\r\n");
      out.write("            </p></div>\r\n");
      out.write("            <div class=\"col-lg-4 mr-auto\"><p class=\"lead\">\r\n");
      out.write("                 6. There are more possibilities to lose or damage mobile phones.\r\n");
      out.write("                <br> 7. Many customers do not want others to know their mobile numbers.\r\n");
      out.write("            </p></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- What are the requirements?-->\r\n");
      out.write("<section class=\"page-section bg-primary text-white mb-0\" id=\"about\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!-- What are the requirements Section Heading-->\r\n");
      out.write("        <h2 class=\"page-section-heading text-center text-uppercase text-white\">What are the requirements?</h2>\r\n");
      out.write("        <!-- Icon Divider-->\r\n");
      out.write("        <div class=\"divider-custom divider-light\">\r\n");
      out.write("            <div class=\"divider-custom-line\"></div>\r\n");
      out.write("            <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("            <div class=\"divider-custom-line\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("            <h4>Agent/Retailers need:</h4>\r\n");
      out.write("        <!-- What are the requirements Section Content-->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-4 ml-auto\"><p class=\"lead\">1. One Account i.e. only one mobile\r\n");
      out.write("                <br> 2. Load Availability\r\n");
      out.write("                <br> 3. Less Investment\r\n");
      out.write("            </p></div>\r\n");
      out.write("            <div class=\"col-lg-4 mr-auto\"><p class=\"lead\">4. Less Risk\r\n");
      out.write("                <br> 5. Less Hassle i.e. easy maintenance\r\n");
      out.write("                <br> 6. More Profit\r\n");
      out.write("            </p></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- The solution:-->\r\n");
      out.write("<section class=\"page-section bg-primary text-white mb-0\" id=\"about\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!--The solution Section Heading-->\r\n");
      out.write("        <h2 class=\"page-section-heading text-center text-uppercase text-white\">The solution:</h2>\r\n");
      out.write("        <!-- Icon Divider-->\r\n");
      out.write("        <div class=\"divider-custom divider-light\">\r\n");
      out.write("            <div class=\"divider-custom-line\"></div>\r\n");
      out.write("            <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("            <div class=\"divider-custom-line\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("            <p>KDRL keeps all these things in consideration and bring up with a unique recharge solution for agents/retailers\r\n");
      out.write("                 where they will find all kinds of recharge only with one mobile.</p>\r\n");
      out.write("        <!-- The solution Section Content-->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-4 ml-auto\"><p class=\"lead\"><i class=\"fas fa-check\"></i> One account\r\n");
      out.write("                <br> <i class=\"fas fa-check\"></i> Recharge any mobile (pre and post-paid) of any mobile operators\r\n");
      out.write("                <br> <i class=\"fas fa-check\"></i> Buy recharge through bKash and Dutch Bangla Mobile Banking\r\n");
      out.write("            </p></div>\r\n");
      out.write("            <div class=\"col-lg-4 mr-auto\"><p class=\"lead\"><i class=\"fas fa-check\"></i> Balance Inquiry\r\n");
      out.write("                <br> <i class=\"fas fa-check\"></i> Recharge Confirmation (one number)\r\n");
      out.write("                <br> <i class=\"fas fa-check\"></i> Mini Statement\r\n");
      out.write("            </p></div>\r\n");
      out.write("            <div class=\"col-lg-4 mr-auto\"><p class=\"lead\"><i class=\"fas fa-check\"></i> PIN Change\r\n");
      out.write("                <br> <i class=\"fas fa-check\"></i> Password Change\r\n");
      out.write("                <br> <i class=\"fas fa-check\"></i> And many more ...\r\n");
      out.write("            </p></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Beneficiaries:-->\r\n");
      out.write("<section class=\"page-section bg-primary text-white mb-0\" id=\"about\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!--BeneficiariesSection Heading-->\r\n");
      out.write("        <h2 class=\"page-section-heading text-center text-uppercase text-white\">Beneficiaries:</h2>\r\n");
      out.write("        <!-- Icon Divider-->\r\n");
      out.write("        <div class=\"divider-custom divider-light\">\r\n");
      out.write("            <div class=\"divider-custom-line\"></div>\r\n");
      out.write("            <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("            <div class=\"divider-custom-line\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Beneficiaries Customers Section Content-->\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"row\"> \r\n");
      out.write("            <h4>Customers:</h4>\r\n");
      out.write("            <div class=\"col-lg-4 ml-auto\"><p class=\"lead\">\r\n");
      out.write("                <i class=\"fas fa-thumbs-up\"></i> Customers will get all mobile operators balance under one roof and they shall not need to go \r\n");
      out.write("                many retailers (as most of the retailers do not have recharge balance of all mobile operators) for different numbers.    \r\n");
      out.write("            </p></div>\r\n");
      out.write("            <div class=\"col-lg-4 mr-auto\"><p class=\"lead\"><i class=\"fas fa-thumbs-up\"></i> There is an option in the KDRL solution for the customers who do not want others to know \r\n");
      out.write("                their mobile numbers i.e. customers can recharge their mobile balance of their own.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\"> \r\n");
      out.write("            <h4>Agents/ Retailers :</h4>\r\n");
      out.write("            <div class=\"col-lg-4 ml-auto\"><p class=\"lead\">\r\n");
      out.write("                <i class=\"fas fa-thumbs-up\"></i>Agents/retailers can run their business easily by using only one account with less investment.\r\n");
      out.write("                <br>\r\n");
      out.write("                <i class=\"fas fa-thumbs-up\"></i>They can buy recharge balance through bKash and mobile banking.\r\n");
      out.write("            </p></div>\r\n");
      out.write("            <div class=\"col-lg-4 mr-auto\"><p class=\"lead\"><i class=\"fas fa-thumbs-up\"></i>Recharge up to 9 different numbers of any mobile \r\n");
      out.write("                operators at the same time and hence reduce recharge time and they can recharge more and do more business.\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"row\"> \r\n");
      out.write("            <h4>Mobile Operators :</h4>\r\n");
      out.write("            <div class=\"col-lg-4 ml-auto\"><p class=\"lead\">\r\n");
      out.write("                <i class=\"fas fa-thumbs-up\"></i>It is difficult for the distributors of all mobile operators to sell recharge balance \r\n");
      out.write("                in rural areas (in village level), \r\n");
      out.write("                </p></div>\r\n");
      out.write("                <div class=\"col-lg-4 mr-auto\"><p class=\"lead\">but through KDRL it is very easy. This will increase recharge balance sell and \r\n");
      out.write("                    increase more profit of Mobile Operators.\r\n");
      out.write("                </p>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<!-- Advantages of KDRL System:-->\r\n");
      out.write("<section class=\"page-section bg-primary text-white mb-0\" id=\"about\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <!--Advantages of KDRL System:-->\r\n");
      out.write("        <h2 class=\"page-section-heading text-center text-uppercase text-white\">Advantages of KDRL System:</h2>\r\n");
      out.write("        <!-- Icon Divider-->\r\n");
      out.write("        <div class=\"divider-custom divider-light\">\r\n");
      out.write("            <div class=\"divider-custom-line\"></div>\r\n");
      out.write("            <div class=\"divider-custom-icon\"><i class=\"fas fa-star\"></i></div>\r\n");
      out.write("            <div class=\"divider-custom-line\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Advantages of KDRL System: Section Content-->\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"col-lg-4 ml-auto\"><p class=\"lead\">\r\n");
      out.write("                <i class=\"fas fa-thumbs-up\"></i> Easy to use and hassle fee.\r\n");
      out.write("                <br> <i class=\"fas fa-thumbs-up\"></i> Less investment and more profit.\r\n");
      out.write("                <br> <i class=\"fas fa-thumbs-up\"></i> Can be run as a side business of others easily (like as grocery shop, medicine shop, laundry, tea stall etc.\r\n");
      out.write("                <br> <i class=\"fas fa-thumbs-up\"></i> Only one SIM and single account, can be recharge in all operators and mobile banking. \r\n");
      out.write("            </p></div>\r\n");
      out.write("            <div class=\"col-lg-4 mr-auto\"><p class=\"lead\">\r\n");
      out.write("                <i class=\"fas fa-thumbs-up\"></i> Does not require 6 mobiles for six operators.\r\n");
      out.write("                <br> <i class=\"fas fa-thumbs-up\"></i> Does not require 6 registers to maintain different accounts.\r\n");
      out.write("                <br> <i class=\"fas fa-thumbs-up\"></i> Free registration for family account.\r\n");
      out.write("            </p></div>\r\n");
      out.write("            <div class=\"col-lg-4 mr-auto\"><p class=\"lead\">\r\n");
      out.write("                <i class=\"fas fa-thumbs-up\"></i> All time recharge balance availability. Agent/retailer can purchase recharge balance from KDRL agent or mobile/internet banking\r\n");
      out.write("                <br> <i class=\"fas fa-thumbs-up\"></i> 24/7 instant customer support.\r\n");
      out.write("                <br> <i class=\"fas fa-thumbs-up\"></i> And many more ...\r\n");
      out.write("            </p></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</section>\r\n");
      out.write("        \r\n");
      out.write("        <!-- Contact Section-->\r\n");
      out.write("      \r\n");
      out.write("        <!-- Footer-->\r\n");
      out.write("       \r\n");
      out.write("        <!-- Copyright Section-->\r\n");
      out.write("        \r\n");
      out.write("        <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes)-->\r\n");
      out.write("       \r\n");
      out.write("      ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
